# K-Means Clustering of microbiome locations

In [1]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D 
%matplotlib inline

from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

## Read in data
1000 rows each showing the locations where an certain micro-organism occured.

In [8]:
dataframe = pd.read_csv("locations_logvals_top1000.csv")
names = dataframe.iloc[:,0:1]
attributes = dataframe.iloc[:,1:11]
data = dataframe.iloc[:,11:1011]

In [9]:
print (dataframe)

    otu name                       GPS Altitude  \
0      AK001      N19.67586 W156.02625       18
1      AK002       N19.56.3 W155.52.10       13
2      AK003     19-22.243N 155-12.37W     1034
3      AK004     19-23.976N 155-15.24W     1132
4      AK005      N19.68079 W156.03000       16
5      AK006     19-40.319N 155-22.30W     1728
6      AK007                       NaN      NaN
7      AK008     19-47.430N 155-19.44W     1899
8      AK009     19-47.325N 155-19.16W     1858
9      AK010      N20.06.962w155.35.40       62
10     AK011        Thurston Lava Tube      NaN
11     AK012     19-23.977N 155-15.23W     1132
12     AK013                       NaN      NaN
13     AK014     19-41.185N 155-27.99W     2087
14     AK015      N19.51.242w155.09.15       30
15     AK016      N20.07.078w155.35.30       30
16     AK017      N19.17.740w155.05.79       41
17     AK018      N19.90927 W155.89438       27
18     AK019      N19.23.965w155.15.23     1140
19     AK020      N19.47.306W155.19.23     1860
20     AK021      N19.90929 W155.89397       27
21     AK022      N19.90960 W155.89249       21
22     AK023  N19 25' 50" W155 15' 53"     3970
23     AK024      N19.90927 W155.89436       27
24     AK025     19-22.219N 155-12.34W     1048
25     AK026   N19 17' 21" W155 7' 46"      120
26     AK027     19-17.387N 155-07.79W       56
27     AK028      N19.68079 W156.02999       16
28     AK029      N19.90960 W155.89250       21
29     AK030      N19.90927 W155.89447       27
..       ...                       ...      ...
71     AK072      N19.46.994W155.18.94     1772
72     AK073     20-07.061N 155-35.07W      289
73     AK074       N19.56.31 W155.52.5       13
74     AK075      N19.23.965w155.15.24     1138
75     AK076  N19 25' 56" W155 15' 53"     3940
76     AK077     20-07.064N 155-35.05W      300
77     AK078                       NaN      NaN
78     AK079                       NaN      NaN
79     AK080  N19 23' 58" W155 15' 14"   3650ft
80     AK081                       NaN      NaN
81     AK082     19-28.991N 154-54.22W      218
82     AK083      N19.90975 W155.89263       24
83     AK084      N19.41.201w155.28.05     2054
84     AK085      N19.23.976w155.15.24     1140
85     AK086      N19.47.373w155.19.50     1908
86     AK087    20-06.985N 155-35.224W      187
87     AK088                       NaN      NaN
88     AK089     19-41.194N 155-27.97W     2090
89     AK090     19-47,508N 155-19.63W     1933
90     AK091      N19.90929 W155.89394       27
91     AK092      N19.90975 W155.89264       24
92     AK093                       NaN      NaN
93     AK094       N19.56.3 W155.52.11       13
94     AK095      N19.90960 W155.89251       21
95     AK096       N18.54.51W155.40.33        8
96     AK097      N19.68733 W156.03193       15
97     AK098      N19.67586 W156.02626       18
98     AK099  N19 23' 58" W155 15' 14"   3650ft
99     AK100  N19 24' 59" W155 14' 21"   3890ft
100    AK101     19-47.391N 155-19.51W     1916

                            Substrate       Date      Time  Temp  Humidity  \
0                   Aimakapa fishpond  1/21/2016      3:21  27.1      63.0
1                    Manoku fish pond  1/21/2016      9:55  24.0      64.9
2                    Lava Rock - 1969  1/14/2016      1227  22.5      63.8
3                                Ohia  1/14/2016      1106  23.2      55.3
4                          Queen bath  1/21/2016      3:55  23.6      63.5
5                      Maura Kea Flow  1/11/2016      1030  21.8      44.9
6                                 NaN        NaN       NaN   NaN       NaN
7                                 Koa   1/7/2016      1436  14.0      84.9
8                            Ohea - J   1/7/2016      1422  14.6      86.4
9              Broadleaf heart shaped   1/9/2016      1:29  26.7      64.6
10                    Left Side Upper  1/14/2016      1040  18.6      73.9
11                     Kilauea - 1974  1/14/2016      1105  23.7      56.3
12                                NaN        NaN       NaN   NaN       NaN
13                                Koa  1/11/2016      1114  21.3      28.0
14                          Star leaf   1/9/2016   1:14 PM  25.0      62.9
15                         Bumpy fern   1/9/2016   1:19 PM  25.0      62.9
16                          Lava rock        NaN      3:10  30.2      55.8
17                    Pristine pool 5  1/21/2016     12:08  25.1      51.2
18      Lava rock underneath the rock        NaN       NaN  20.4      64.9
19                                Kia   1/7/2016      2:18  15.4      81.2
20                  Pristine pool 3/4  1/21/2016     11:58  26.2      50.3
21                    Pristine pool 1  1/21/2016     11:40  25.3      57.7
22   Steam vent with a lot of foliage  1/15/2016  10:46 AM  21.0      50.1
23                    Pristine pool 5  1/21/2016     12:08  25.1      51.2
24                               Ohia  1/14/2016      1225  21.5      66.1
25                    Petroglyph Rock  1/14/2016       NaN  29.3      57.2
26                         Petroglyph  1/14/2016      1443  29.5      57.1
27                         Queen bath  1/21/2016      3:55  23.6      63.5
28                    Pristine pool 1  1/21/2016     11:40  25.3      57.7
29                    Pristine pool 8  1/21/2016     12:27  24.2      51.2
..                                ...        ...       ...   ...       ...
71                               Ohia   1/7/2016     13:45  17.2      72.9
72                               Pine   1/9/2016      1440  24.7      76.5
73                  Hopeaia fish pond  1/21/2016      9:48  24.0      65.3
74                          Ohia tree        NaN     11:08  20.4      64.9
75                         Steam vent  1/15/2016  10:23 AM  23.4      46.3
76                              SWISS   1/9/2016      1452  25.9      67.7
77                                NaN        NaN       NaN   NaN       NaN
78                                NaN        NaN       NaN   NaN       NaN
79                               Rock  1/14/2016       NaN  23.0      56.3
80                                NaN        NaN       NaN   NaN       NaN
81                         BIG LEAVES  1/10/2016      1131  36.0      36.0
82                    Pristine pool 2  1/21/2016     11:50  24.1      55.7
83                                Koa  1/11/2016     10:57  16.1      25.3
84                           Red rock        NaN       NaN  20.4      64.9
85                               Ohia   1/7/2016      2:20  15.3      79.5
86   Plant with red and black berries   1/9/2016      1426  27.5      66.1
87                                NaN        NaN       NaN   NaN       NaN
88                   Green leaf plant  1/11/2016      1110  21.4      23.4
89                               Ohia   1/7/2016      1456  15.8      81.3
90                  Pristine pool 3/4  1/21/2016     11:58  23.3      50.3
91                    Pristine pool 2  1/21/2016     11:50  24.1      55.7
92                                NaN        NaN       NaN   NaN       NaN
93                   Manoku fish pond  1/21/2016      9:55  24.0      64.9
94                    Pristine pool 1  1/21/2016     11:40  25.3      57.7
95                     Lua o palahemo  1/17/2016      3:56  24.1      65.4
96                    Kaloko fishpond  1/21/2016      2:50  27.1      55.7
97                  Aimakapa fishpond  1/21/2016      3:21  27.1      63.0
98                               Rock  1/14/2016       NaN  23.0      56.3
99                          Lava tube  1/14/2016       NaN  19.1      71.0
100                               KOA   1/7/2016      1445  16.1      81.2

                    Weather  Wind Speed    ...      OTU_435  OTU_1800  \
0                     Sunny         1.9    ...     0.000000  0.698970
1                     Sunny         0.2    ...     0.000000  0.000000
2                  Overcast         NaN    ...     0.000000  0.301030
3                     Sunny         NaN    ...     0.000000  0.301030
4                     Sunny         0.4    ...     0.000000  0.000000
5                       Sun         0.5    ...     0.301030  0.000000
6                       NaN         NaN    ...     0.000000  0.000000
7                     Foggy         0.0    ...     0.301030  0.301030
8                     Foggy         0.0    ...     0.000000  0.000000
9                       Sun         0.0    ...     0.000000  0.000000
10                  In cave         0.0    ...     0.000000  0.000000
11                    Sunny         NaN    ...     0.000000  0.301030
12                      NaN         NaN    ...     0.000000  0.000000
13                    Shade         0.0    ...     0.477121  0.000000
14                      Sun         0.0    ...     0.000000  0.301030
15                      Sun         0.0    ...     0.000000  0.000000
16                      NaN         0.4    ...     0.000000  0.000000
17                    Sunny         5.0    ...     0.000000  0.000000
18                      Sun         2.0    ...     0.000000  0.477121
19                 Overcast         0.4    ...     0.301030  0.301030
20                    Sunny         0.7    ...     0.778151  0.301030
21                    Sunny         3.1    ...     0.000000  0.000000
22                    Sunny         1.8    ...     0.000000  0.301030
23                    Sunny         5.0    ...     0.000000  0.000000
24                 Overcast         NaN    ...     0.000000  0.301030
25                    Sunny         0.8    ...     0.000000  0.301030
26                    Sunny         7.5    ...     0.000000  0.000000
27                    Sunny         0.4    ...     0.477121  0.301030
28                    Sunny         3.1    ...     0.000000  0.778151
29                    Sunny         5.0    ...     0.301030  0.000000
..                      ...         ...    ...          ...       ...
71                 Overcast         0.0    ...     0.301030  0.000000
72          Shade - seaside         1.1    ...     0.000000  0.301030
73                    Sunny         0.6    ...     0.000000  0.301030
74                      Sun         2.0    ...     0.698970  0.477121
75                    Sunny         2.5    ...     0.477121  0.000000
76   In sun - top of valley         0.1    ...     2.599883  0.000000
77                      NaN         NaN    ...     0.000000  0.000000
78                      NaN         NaN    ...     0.301030  0.602060
79                    Sunny         1.5    ...     0.000000  0.000000
80                      NaN         NaN    ...     0.301030  0.000000
81          In sun off path         0.0    ...     0.000000  0.477121
82                    Sunny         1.5    ...     0.477121  0.477121
83                      Sun         1.3    ...     0.000000  0.000000
84                      Sun         0.0    ...     0.000000  0.000000
85                 Overcast         0.4    ...     0.000000  0.000000
86           Humid in shade         0.0    ...     0.698970  0.000000
87                      NaN         NaN    ...     0.000000  0.000000
88                      Sun         0.6    ...     0.477121  0.477121
89           Slightly foggy         0.0    ...     0.000000  0.000000
90                    Sunny         0.7    ...     0.000000  0.477121
91                    Sunny         1.5    ...     0.301030  0.000000
92                      NaN         NaN    ...     0.000000  0.000000
93                    Sunny         0.2    ...     0.602060  0.000000
94                    Sunny         3.1    ...     0.000000  0.000000
95                      NaN         4.5    ...     0.301030  0.477121
96                    Sunny         2.5    ...     0.301030  0.000000
97                    Sunny         1.9    ...     0.000000  0.000000
98                    Sunny         1.5    ...     0.000000  0.000000
99                    Sunny         NaN    ...     0.301030  0.000000
100                   Foggy         0.0    ...     0.000000  0.301030

      OTU_813   OTU_307  OTU_9538  OTU_13422   OTU_502  OTU_6011   OTU_873  \
0    0.477121  0.000000  0.602060   0.903090  3.203577  0.301030  0.301030
1    0.000000  0.000000  0.301030   0.602060  0.477121  0.000000  0.000000
2    0.000000  0.000000  0.000000   0.477121  0.301030  0.000000  0.000000
3    0.000000  0.000000  0.000000   0.477121  0.477121  0.000000  0.301030
4    0.000000  0.000000  0.845098   0.778151  0.845098  0.698970  0.000000
5    0.000000  0.000000  0.903090   0.301030  0.698970  1.591065  0.000000
6    0.000000  0.000000  0.000000   0.301030  0.000000  0.000000  0.000000
7    0.477121  0.000000  0.477121   0.698970  0.698970  0.301030  0.000000
8    0.000000  0.000000  0.000000   0.477121  0.000000  0.000000  0.000000
9    0.000000  0.000000  1.176091   0.301030  0.301030  0.301030  0.000000
10   0.000000  0.000000  2.622214   0.778151  0.903090  1.690196  0.000000
11   0.000000  0.000000  0.778151   0.301030  0.477121  0.000000  0.301030
12   0.000000  0.000000  0.301030   0.301030  0.602060  0.301030  0.301030
13   0.000000  0.000000  0.903090   0.698970  0.903090  0.000000  0.301030
14   0.000000  0.000000  0.778151   0.477121  0.000000  0.000000  0.301030
15   0.301030  0.000000  0.903090   0.903090  1.204120  0.477121  1.880814
16   0.000000  0.000000  0.477121   0.477121  0.301030  0.000000  0.301030
17   0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  0.000000
18   0.000000  0.000000  0.000000   0.602060  0.602060  0.000000  0.000000
19   0.000000  0.000000  0.778151   0.903090  0.477121  0.000000  0.000000
20   0.845098  0.000000  0.602060   1.431364  1.230449  0.301030  0.301030
21   1.113943  0.000000  0.778151   0.778151  0.954243  0.000000  0.301030
22   0.477121  0.000000  1.000000   1.380211  1.204120  0.477121  0.602060
23   2.225309  0.000000  0.698970   0.477121  0.000000  0.000000  0.000000
24   0.000000  0.000000  0.000000   0.000000  0.301030  0.000000  0.000000
25   0.954243  0.000000  0.903090   1.380211  1.255273  0.301030  0.301030
26   0.477121  0.000000  0.301030   0.845098  0.477121  0.000000  0.301030
27   0.602060  0.000000  1.041393   1.278754  1.361728  0.301030  0.301030
28   2.264818  0.000000  0.698970   1.278754  1.146128  0.000000  0.000000
29   0.778151  0.000000  0.477121   0.477121  0.477121  0.000000  0.000000
..        ...       ...       ...        ...       ...       ...       ...
71   0.000000  0.602060  0.000000   0.000000  0.000000  0.000000  0.778151
72   0.000000  1.041393  0.301030   0.000000  0.000000  0.602060  0.301030
73   0.000000  0.602060  0.000000   0.000000  0.000000  0.000000  0.000000
74   0.301030  0.954243  0.000000   0.000000  0.000000  0.698970  0.954243
75   0.000000  0.301030  0.000000   0.000000  0.000000  0.301030  0.301030
76   0.000000  0.301030  0.000000   0.000000  0.000000  0.698970  0.301030
77   0.000000  0.301030  0.000000   0.000000  0.000000  0.698970  0.000000
78   0.000000  0.301030  0.000000   0.000000  0.000000  0.301030  0.000000
79   0.000000  1.000000  0.000000   0.000000  0.000000  0.000000  0.477121
80   0.000000  0.602060  0.000000   0.000000  0.000000  0.000000  0.000000
81   0.000000  0.602060  0.000000   0.000000  0.000000  0.000000  0.301030
82   0.301030  1.579784  0.477121   0.000000  0.000000  0.698970  0.778151
83   0.000000  0.000000  0.000000   0.000000  0.000000  1.079181  0.301030
84   0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  0.000000
85   0.000000  0.301030  2.000000   0.000000  0.000000  0.477121  1.959041
86   0.000000  0.301030  0.000000   0.000000  0.000000  0.301030  0.301030
87   0.301030  0.000000  0.301030   0.000000  0.000000  0.000000  0.301030
88   0.301030  0.602060  0.845098   0.000000  0.000000  1.431364  0.477121
89   0.000000  0.778151  0.000000   0.000000  0.000000  0.477121  0.301030
90   0.000000  1.204120  0.000000   0.000000  0.000000  0.000000  0.000000
91   0.000000  0.602060  0.000000   0.000000  0.000000  0.000000  0.000000
92   0.000000  0.602060  0.000000   0.000000  0.000000  0.000000  0.602060
93   0.301030  1.079181  0.000000   0.000000  0.000000  0.602060  0.477121
94   0.000000  0.000000  0.000000   0.000000  0.000000  0.301030  0.301030
95   0.301030  3.377124  0.000000   0.000000  0.000000  0.954243  0.477121
96   0.000000  2.876795  0.000000   0.000000  0.000000  0.000000  0.301030
97   0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  0.000000
98   0.000000  0.000000  0.000000   0.000000  0.000000  0.000000  0.000000
99   0.000000  0.000000  0.301030   0.000000  0.000000  1.176091  0.477121
100  0.000000  0.000000  0.000000   0.000000  0.000000  0.301030  0.477121

      OTU_300
0    0.000000
1    0.000000
2    0.000000
3    0.000000
4    0.000000
5    0.000000
6    0.000000
7    0.000000
8    0.000000
9    0.000000
10   0.000000
11   0.000000
12   0.000000
13   0.000000
14   0.000000
15   0.000000
16   0.000000
17   0.000000
18   0.000000
19   0.000000
20   0.000000
21   0.000000
22   0.000000
23   0.000000
24   0.000000
25   0.000000
26   0.000000
27   0.000000
28   0.000000
29   0.000000
..        ...
71   2.278754
72   0.477121
73   0.477121
74   1.672098
75   2.238046
76   2.946943
77   1.278754
78   0.000000
79   0.000000
80   0.301030
81   2.469822
82   3.275311
83   0.477121
84   0.000000
85   0.477121
86   0.301030
87   0.477121
88   0.301030
89   0.903090
90   0.301030
91   0.000000
92   0.477121
93   1.146128
94   0.301030
95   0.698970
96   0.000000
97   0.000000
98   0.000000
99   0.602060
100  0.301030

[101 rows x 1011 columns]

In [10]:
print (data)

       OTU_12    OTU_11     OTU_5     OTU_9    OTU_45    OTU_23    OTU_52  \
0    4.417289  3.766710  2.633468  3.795115  2.611723  3.885813  2.824126
1    4.160948  3.547775  2.235528  3.385964  3.249443  3.449787  1.707570
2    4.009578  2.346353  3.521269  3.508664  3.333447  2.053078  1.531479
3    2.937016  3.072250  3.415140  2.012837  2.725912  1.591065  1.230449
4    3.198657  3.014100  1.770852  2.953760  2.739572  2.777427  1.041393
5    3.046495  3.196453  2.453318  2.468347  2.477121  2.521138  2.117271
6    3.197281  2.906335  4.016616  2.739572  2.089905  2.522444  1.414973
7    3.164353  1.556303  1.591065  2.456366  2.708421  2.691965  1.146128
8    3.317854  4.141638  1.792392  2.943989  2.264818  3.115278  2.502427
9    3.540455  1.963788  1.301030  3.071145  1.462398  1.230449  0.477121
10   3.486855  2.713491  3.263399  2.190332  2.326336  1.477121  2.679428
11   3.303844  4.379487  3.592066  2.860937  2.657056  2.178977  2.899821
12   3.139564  2.987219  3.477121  2.812913  3.777354  2.350248  2.260071
13   3.485011  2.925828  3.927422  1.556303  2.758912  1.851258  2.670246
14   3.486289  3.337060  2.829304  2.776701  1.755875  2.678518  0.954243
15   2.977266  2.801404  1.886491  2.170262  1.633468  2.130334  1.255273
16   3.576341  3.606596  2.824776  2.988559  2.751279  1.716003  2.989005
17   3.447003  3.319522  3.538699  2.409933  2.600973  2.840106  2.445604
18   3.451479  3.264582  2.474216  2.418301  2.783904  1.716003  1.255273
19   2.257679  2.917506  4.177017  1.954243  2.320146  2.195900  1.531479
20   2.575188  2.170262  2.079181  2.255273  3.085291  2.336460  2.029384
21   2.938019  2.107210  1.579784  2.442480  2.753583  2.292256  1.278754
22   2.460898  2.181844  1.934498  2.298853  2.996949  2.340444  1.748188
23   3.261976  3.078457  2.454845  2.995635  2.727541  1.602060  3.285782
24   3.165244  3.767527  2.931966  3.045714  2.895975  2.507856  1.230449
25   2.639486  2.336460  1.819544  2.053078  3.180699  2.307496  1.579784
26   3.140822  2.569374  2.167317  2.453318  2.990339  2.271842  2.198657
27   2.775246  2.532754  2.012837  2.431364  3.465532  2.506505  1.863323
28   2.695482  2.220108  1.806180  2.278754  2.604226  2.298853  1.880814
29   3.027757  2.332438  1.633468  2.195900  2.980003  1.690196  1.146128
..        ...       ...       ...       ...       ...       ...       ...
71   3.257918  2.562293  2.990339  2.810233  2.320146  2.778874  2.705008
72   3.066699  4.505001  2.972203  2.700704  2.120574  2.346353  2.041393
73   2.944483  3.691347  3.697317  2.617000  1.544068  1.724276  1.819544
74   3.937418  3.756560  3.705436  3.621488  3.144885  3.797890  2.617000
75   3.324077  3.902601  3.517196  1.491362  2.562293  2.705008  2.586587
76   3.937869  3.970347  3.768416  2.117271  3.161068  3.356599  2.389166
77   2.684845  2.053078  2.754348  2.250420  2.136721  2.267172  1.698970
78   3.714497  2.658011  3.149527  2.729974  1.397940  1.278754  2.123852
79   3.293363  3.406370  2.983175  1.568202  1.230449  1.146128  1.806180
80   2.720986  2.720986  2.931458  2.257679  1.505150  2.120574  2.252853
81   3.609701  3.259355  3.612148  3.201670  1.785330  2.041393  3.354108
82   2.462398  3.376577  2.326336  1.963788  1.732394  1.799341  2.492760
83   3.212720  2.856729  1.991226  2.365488  1.113943  2.053078  1.792392
84   2.853090  2.155336  2.107210  3.027757  1.278754  2.539076  2.593286
85   2.920123  2.485721  1.380211  2.788168  2.606381  2.509203  2.000000
86   2.968950  2.451786  1.462398  2.559907  1.851258  2.117271  1.929419
87   3.512951  3.496238  1.041393  2.309630  2.710117  3.371622  3.188928
88   2.761928  2.933487  2.614897  2.431364  2.033424  2.123852  2.313867
89   2.846337  2.848189  1.462398  2.408240  1.707570  2.257679  4.459995
90   2.883661  3.362294  2.012837  2.245513  2.056905  1.851258  2.820201
91   3.350442  3.297542  1.698970  3.026533  3.484727  1.973128  1.623249
92   2.916980  2.546543  0.845098  1.342423  1.740363  1.857332  2.250420
93   2.322219  2.800717  1.748188  1.838849  1.806180  1.880814  2.257679
94   3.002166  3.543199  2.204120  1.322219  3.096910  2.805501  1.623249
95   2.436163  2.868644  1.908485  2.068186  1.591065  1.826075  2.411620
96   3.504878  3.765147  2.155336  1.826075  2.783904  1.623249  3.093772
97   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.301030
98   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.301030
99   3.850646  2.714330  2.829947  1.414973  3.353724  2.889862  1.959041
100  3.542327  3.098298  1.278754  2.947434  1.986772  1.832509  2.546543

     OTU_12993  OTU_11397  OTU_12053    ...      OTU_435  OTU_1800   OTU_813  \
0     3.471585   2.245513   2.740363    ...     0.000000  0.698970  0.477121
1     3.175802   1.944483   2.640481    ...     0.000000  0.000000  0.000000
2     3.152288   3.157759   1.342423    ...     0.000000  0.301030  0.000000
3     1.963788   3.629206   2.146128    ...     0.000000  0.301030  0.000000
4     2.227887   1.414973   2.075547    ...     0.000000  0.000000  0.000000
5     2.136721   1.959041   2.283301    ...     0.301030  0.000000  0.000000
6     2.167317   2.961895   2.017033    ...     0.000000  0.000000  0.000000
7     2.158362   1.397940   0.845098    ...     0.301030  0.301030  0.477121
8     2.356026   1.447158   3.235781    ...     0.000000  0.000000  0.000000
9     2.610660   0.954243   0.477121    ...     0.000000  0.000000  0.000000
10    2.519828   2.037426   1.892095    ...     0.000000  0.000000  0.000000
11    2.012837   2.870989   3.470116    ...     0.000000  0.301030  0.000000
12    2.201397   2.872739   1.748188    ...     0.000000  0.000000  0.000000
13    2.540329   3.230193   1.934498    ...     0.477121  0.000000  0.000000
14    2.489958   1.602060   2.437751    ...     0.000000  0.301030  0.000000
15    2.060698   2.281033   1.913814    ...     0.000000  0.000000  0.301030
16    2.605305   2.799341   2.693727    ...     0.000000  0.000000  0.000000
17    2.469822   2.290035   2.281033    ...     0.000000  0.000000  0.000000
18    2.506505   1.785330   2.127105    ...     0.000000  0.477121  0.000000
19    1.361728   3.938670   2.017033    ...     0.301030  0.301030  0.000000
20    1.579784   1.716003   1.278754    ...     0.778151  0.301030  0.845098
21    1.995635   1.322219   1.176091    ...     0.000000  0.000000  1.113943
22    1.518514   1.491362   1.204120    ...     0.000000  0.301030  0.477121
23    2.287802   1.278754   2.193125    ...     0.000000  0.000000  2.225309
24    2.214844   1.763428   2.854913    ...     0.000000  0.301030  0.000000
25    1.672098   1.361728   1.556303    ...     0.000000  0.301030  0.954243
26    2.155336   1.968483   1.633468    ...     0.000000  0.000000  0.477121
27    1.919078   1.724276   1.690196    ...     0.477121  0.301030  0.602060
28    1.812913   1.431364   1.204120    ...     0.000000  0.778151  2.264818
29    2.139879   1.414973   1.462398    ...     0.301030  0.000000  0.778151
..         ...        ...        ...    ...          ...       ...       ...
71    2.392697   2.419956   1.556303    ...     0.301030  0.000000  0.000000
72    2.053078   2.905256   3.506911    ...     0.000000  0.301030  0.000000
73    2.008600   3.101747   2.755112    ...     0.000000  0.301030  0.000000
74    2.930949   2.686636   2.845098    ...     0.698970  0.477121  0.301030
75    2.346353   2.758155   2.989450    ...     0.477121  0.000000  0.000000
76    3.004751   3.323046   3.046495    ...     2.599883  0.000000  0.000000
77    1.681241   1.690196   1.176091    ...     0.000000  0.000000  0.000000
78    2.773055   1.986772   1.724276    ...     0.301030  0.602060  0.000000
79    2.173186   2.342423   2.450249    ...     0.000000  0.000000  0.000000
80    1.845098   2.139879   1.707570    ...     0.301030  0.000000  0.000000
81    2.662758   3.341632   2.409933    ...     0.000000  0.477121  0.000000
82    1.322219   2.029384   2.457882    ...     0.477121  0.477121  0.301030
83    2.204120   2.357935   1.924279    ...     0.000000  0.000000  0.000000
84    1.919078   2.037426   1.230449    ...     0.000000  0.000000  0.000000
85    2.000000   1.079181   1.591065    ...     0.000000  0.000000  0.000000
86    2.045323   1.255273   1.591065    ...     0.698970  0.000000  0.000000
87    2.563481   1.079181   2.637490    ...     0.000000  0.000000  0.301030
88    1.819544   2.720986   1.531479    ...     0.477121  0.477121  0.301030
89    1.968483   1.255273   1.886491    ...     0.000000  0.000000  0.000000
90    1.982271   1.505150   2.447158    ...     0.000000  0.477121  0.000000
91    2.481443   2.448706   2.390935    ...     0.301030  0.000000  0.000000
92    1.913814   0.954243   1.732394    ...     0.000000  0.000000  0.000000
93    1.204120   1.491362   1.826075    ...     0.602060  0.000000  0.301030
94    2.082785   1.623249   2.637490    ...     0.000000  0.000000  0.000000
95    1.462398   1.707570   2.021189    ...     0.301030  0.477121  0.301030
96    2.639486   2.598791   2.870989    ...     0.301030  0.000000  0.000000
97    0.000000   0.000000   0.000000    ...     0.000000  0.000000  0.000000
98    0.000000   0.000000   0.000000    ...     0.000000  0.000000  0.000000
99    2.904716   1.886491   1.832509    ...     0.301030  0.000000  0.000000
100   2.656098   1.146128   2.164353    ...     0.000000  0.301030  0.000000

      OTU_307  OTU_9538  OTU_13422   OTU_502  OTU_6011   OTU_873   OTU_300
0    0.000000  0.602060   0.903090  3.203577  0.301030  0.301030  0.000000
1    0.000000  0.301030   0.602060  0.477121  0.000000  0.000000  0.000000
2    0.000000  0.000000   0.477121  0.301030  0.000000  0.000000  0.000000
3    0.000000  0.000000   0.477121  0.477121  0.000000  0.301030  0.000000
4    0.000000  0.845098   0.778151  0.845098  0.698970  0.000000  0.000000
5    0.000000  0.903090   0.301030  0.698970  1.591065  0.000000  0.000000
6    0.000000  0.000000   0.301030  0.000000  0.000000  0.000000  0.000000
7    0.000000  0.477121   0.698970  0.698970  0.301030  0.000000  0.000000
8    0.000000  0.000000   0.477121  0.000000  0.000000  0.000000  0.000000
9    0.000000  1.176091   0.301030  0.301030  0.301030  0.000000  0.000000
10   0.000000  2.622214   0.778151  0.903090  1.690196  0.000000  0.000000
11   0.000000  0.778151   0.301030  0.477121  0.000000  0.301030  0.000000
12   0.000000  0.301030   0.301030  0.602060  0.301030  0.301030  0.000000
13   0.000000  0.903090   0.698970  0.903090  0.000000  0.301030  0.000000
14   0.000000  0.778151   0.477121  0.000000  0.000000  0.301030  0.000000
15   0.000000  0.903090   0.903090  1.204120  0.477121  1.880814  0.000000
16   0.000000  0.477121   0.477121  0.301030  0.000000  0.301030  0.000000
17   0.000000  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000
18   0.000000  0.000000   0.602060  0.602060  0.000000  0.000000  0.000000
19   0.000000  0.778151   0.903090  0.477121  0.000000  0.000000  0.000000
20   0.000000  0.602060   1.431364  1.230449  0.301030  0.301030  0.000000
21   0.000000  0.778151   0.778151  0.954243  0.000000  0.301030  0.000000
22   0.000000  1.000000   1.380211  1.204120  0.477121  0.602060  0.000000
23   0.000000  0.698970   0.477121  0.000000  0.000000  0.000000  0.000000
24   0.000000  0.000000   0.000000  0.301030  0.000000  0.000000  0.000000
25   0.000000  0.903090   1.380211  1.255273  0.301030  0.301030  0.000000
26   0.000000  0.301030   0.845098  0.477121  0.000000  0.301030  0.000000
27   0.000000  1.041393   1.278754  1.361728  0.301030  0.301030  0.000000
28   0.000000  0.698970   1.278754  1.146128  0.000000  0.000000  0.000000
29   0.000000  0.477121   0.477121  0.477121  0.000000  0.000000  0.000000
..        ...       ...        ...       ...       ...       ...       ...
71   0.602060  0.000000   0.000000  0.000000  0.000000  0.778151  2.278754
72   1.041393  0.301030   0.000000  0.000000  0.602060  0.301030  0.477121
73   0.602060  0.000000   0.000000  0.000000  0.000000  0.000000  0.477121
74   0.954243  0.000000   0.000000  0.000000  0.698970  0.954243  1.672098
75   0.301030  0.000000   0.000000  0.000000  0.301030  0.301030  2.238046
76   0.301030  0.000000   0.000000  0.000000  0.698970  0.301030  2.946943
77   0.301030  0.000000   0.000000  0.000000  0.698970  0.000000  1.278754
78   0.301030  0.000000   0.000000  0.000000  0.301030  0.000000  0.000000
79   1.000000  0.000000   0.000000  0.000000  0.000000  0.477121  0.000000
80   0.602060  0.000000   0.000000  0.000000  0.000000  0.000000  0.301030
81   0.602060  0.000000   0.000000  0.000000  0.000000  0.301030  2.469822
82   1.579784  0.477121   0.000000  0.000000  0.698970  0.778151  3.275311
83   0.000000  0.000000   0.000000  0.000000  1.079181  0.301030  0.477121
84   0.000000  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000
85   0.301030  2.000000   0.000000  0.000000  0.477121  1.959041  0.477121
86   0.301030  0.000000   0.000000  0.000000  0.301030  0.301030  0.301030
87   0.000000  0.301030   0.000000  0.000000  0.000000  0.301030  0.477121
88   0.602060  0.845098   0.000000  0.000000  1.431364  0.477121  0.301030
89   0.778151  0.000000   0.000000  0.000000  0.477121  0.301030  0.903090
90   1.204120  0.000000   0.000000  0.000000  0.000000  0.000000  0.301030
91   0.602060  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000
92   0.602060  0.000000   0.000000  0.000000  0.000000  0.602060  0.477121
93   1.079181  0.000000   0.000000  0.000000  0.602060  0.477121  1.146128
94   0.000000  0.000000   0.000000  0.000000  0.301030  0.301030  0.301030
95   3.377124  0.000000   0.000000  0.000000  0.954243  0.477121  0.698970
96   2.876795  0.000000   0.000000  0.000000  0.000000  0.301030  0.000000
97   0.000000  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000
98   0.000000  0.000000   0.000000  0.000000  0.000000  0.000000  0.000000
99   0.000000  0.301030   0.000000  0.000000  1.176091  0.477121  0.602060
100  0.000000  0.000000   0.000000  0.000000  0.301030  0.477121  0.301030

[101 rows x 1000 columns]

In [11]:
# do the clustering
#k_means = sklearn.cluster.KMeans(n_clusters=3)
k_means = KMeans(n_clusters=10)           # imported above
k_means.fit(data) 
labels = k_means.labels_

In [12]:
print (labels)

[4 0 0 0 4 4 0 0 0 0 4 4 0 4 0 4 0 0 4 4 7 1 7 4 0 7 1 7 7 1 7 1 1 7 7 0 7
 0 5 4 5 5 5 7 0 4 1 4 0 0 4 9 2 2 2 2 2 2 6 6 9 6 6 2 3 3 6 3 9 8 9 8 8 8
 9 8 2 8 8 8 8 8 9 2 8 2 2 8 2 2 8 8 8 9 8 9 8 8 8 2 2]

In [13]:
dataframe['category'] = labels

In [14]:
dataframe.loc[dataframe['category'] == 8]

,otu name,GPS,Altitude,Substrate,Date,Time,Temp,Humidity,Weather,Wind Speed,...,OTU_1800,OTU_813,OTU_307,OTU_9538,OTU_13422,OTU_502,OTU_6011,OTU_873,OTU_300,category
69,AK070,19-18.471N 155-18.30W,824,ohia,1/15/2016,1346,24.0,62.7,overcast,0.3,...,0.000000,0.00000,0.301030,0.00000,0.0,0.0,0.00000,0.000000,0.301030,8
71,AK072,N19.46.994W155.18.94,1772,Ohia,1/7/2016,13:45,17.2,72.9,Overcast,0.0,...,0.000000,0.00000,0.602060,0.00000,0.0,0.0,0.00000,0.778151,2.278754,8
72,AK073,20-07.061N 155-35.07W,289,Pine,1/9/2016,1440,24.7,76.5,Shade - seaside,1.1,...,0.301030,0.00000,1.041393,0.30103,0.0,0.0,0.60206,0.301030,0.477121,8
73,AK074,N19.56.31 W155.52.5,13,Hopeaia fish pond,1/21/2016,9:48,24.0,65.3,Sunny,0.6,...,0.301030,0.00000,0.602060,0.00000,0.0,0.0,0.00000,0.000000,0.477121,8
75,AK076,"N19 25' 56"" W155 15' 53""",3940,Steam vent,1/15/2016,10:23 AM,23.4,46.3,Sunny,2.5,...,0.000000,0.00000,0.301030,0.00000,0.0,0.0,0.30103,0.301030,2.238046,8
77,AK078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.00000,0.301030,0.00000,0.0,0.0,0.69897,0.000000,1.278754,8
78,AK079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.602060,0.00000,0.301030,0.00000,0.0,0.0,0.30103,0.000000,0.000000,8
79,AK080,"N19 23' 58"" W155 15' 14""",3650ft,Rock,1/14/2016,NaN,23.0,56.3,Sunny,1.5,...,0.000000,0.00000,1.000000,0.00000,0.0,0.0,0.00000,0.477121,0.000000,8
80,AK081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.00000,0.602060,0.00000,0.0,0.0,0.00000,0.000000,0.301030,8
81,AK082,19-28.991N 154-54.22W,218,BIG LEAVES,1/10/2016,1131,36.0,36.0,In sun off path,0.0,...,0.477121,0.00000,0.602060,0.00000,0.0,0.0,0.00000,0.301030,2.469822,8
84,AK085,N19.23.976w155.15.24,1140,Red rock,NaN,NaN,20.4,64.9,Sun,0.0,...,0.000000,0.00000,0.000000,0.00000,0.0,0.0,0.00000,0.000000,0.000000,8
87,AK088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.30103,0.000000,0.30103,0.0,0.0,0.00000,0.301030,0.477121,8
90,AK091,N19.90929 W155.89394,27,Pristine pool 3/4,1/21/2016,11:58,23.3,50.3,Sunny,0.7,...,0.477121,0.00000,1.204120,0.00000,0.0,0.0,0.00000,0.000000,0.301030,8
91,AK092,N19.90975 W155.89264,24,Pristine pool 2,1/21/2016,11:50,24.1,55.7,Sunny,1.5,...,0.000000,0.00000,0.602060,0.00000,0.0,0.0,0.00000,0.000000,0.000000,8
92,AK093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.00000,0.602060,0.00000,0.0,0.0,0.00000,0.602060,0.477121,8
94,AK095,N19.90960 W155.89251,21,Pristine pool 1,1/21/2016,11:40,25.3,57.7,Sunny,3.1,...,0.000000,0.00000,0.000000,0.00000,0.0,0.0,0.30103,0.301030,0.301030,8
96,AK097,N19.68733 W156.03193,15,Kaloko fishpond,1/21/2016,2:50,27.1,55.7,Sunny,2.5,...,0.000000,0.00000,2.876795,0.00000,0.0,0.0,0.00000,0.301030,0.000000,8
97,AK098,N19.67586 W156.02626,18,Aimakapa fishpond,1/21/2016,3:21,27.1,63.0,Sunny,1.9,...,0.000000,0.00000,0.000000,0.00000,0.0,0.0,0.00000,0.000000,0.000000,8
98,AK099,"N19 23' 58"" W155 15' 14""",3650ft,Rock,1/14/2016,NaN,23.0,56.3,Sunny,1.5,...,0.000000,0.00000,0.000000,0.00000,0.0,0.0,0.00000,0.000000,0.000000,8

In [15]:
dataframe['category'].value_counts()

8    19
0    17
2    15
4    14
7    10
9     8
1     6
6     5
5     4
3     3
Name: category, dtype: int64

In [16]:
dataframe.groupby('category').first()

,otu name,GPS,Altitude,Substrate,Date,Time,Temp,Humidity,Weather,Wind Speed,...,OTU_435,OTU_1800,OTU_813,OTU_307,OTU_9538,OTU_13422,OTU_502,OTU_6011,OTU_873,OTU_300
category,,,,,,,,,,,,,,,,,,,,,
0,AK002,N19.56.3 W155.52.10,13,Manoku fish pond,1/21/2016,9:55,24.0,64.9,Sunny,0.2,...,0.000000,0.000000,0.000000,0.000000,0.301030,0.602060,0.477121,0.000000,0.000000,0.000000
1,AK022,N19.90960 W155.89249,21,Pristine pool 1,1/21/2016,11:40,25.3,57.7,Sunny,3.1,...,0.000000,0.000000,1.113943,0.000000,0.778151,0.778151,0.954243,0.000000,0.301030,0.000000
2,AK053,N19.47.480w155.19.64,1933,Ohia,1/7/2016,2:50,14.9,81.8,Overcast,0.0,...,0.477121,0.000000,0.301030,0.301030,0.301030,0.000000,0.000000,0.477121,0.000000,0.000000
3,AK065,N19.56.31 W155.52.7,13,Hopeaia fish pond,1/21/2016,9:48,24.0,65.3,Sunny,0.6,...,1.041393,0.698970,2.093422,0.954243,0.000000,0.000000,0.000000,0.602060,0.778151,0.845098
4,AK001,N19.67586 W156.02625,18,Aimakapa fishpond,1/21/2016,3:21,27.1,63.0,Sunny,1.9,...,0.000000,0.698970,0.477121,0.000000,0.602060,0.903090,3.203577,0.301030,0.301030,0.000000
5,AK039,n19 40 18 w 155 22 18,5730,Rock,1/11/2016,10:19,21.6,49.9,Sunny,2.5,...,0.000000,1.724276,0.000000,0.000000,0.301030,0.778151,0.477121,0.000000,0.000000,0.000000
6,AK059,N20.06.993.w155.35.23,210,Green tear shaped four veins run vertical mult...,1/9/2016,2:23,27.3,62.3,Sun,0.0,...,1.568202,1.819544,0.845098,1.079181,0.301030,0.000000,0.000000,0.602060,1.568202,0.903090
7,AK021,N19.90929 W155.89397,27,Pristine pool 3/4,1/21/2016,11:58,26.2,50.3,Sunny,0.7,...,0.778151,0.301030,0.845098,0.000000,0.602060,1.431364,1.230449,0.301030,0.301030,0.000000
8,AK070,19-18.471N 155-18.30W,824,ohia,1/15/2016,1346,24.0,62.7,overcast,0.3,...,0.477121,0.000000,0.000000,0.301030,0.000000,0.000000,0.000000,0.000000,0.000000,0.301030
9,AK052,N19.46.994W155.18.94,1772,Koa tree,1/7/2016,1:41 PM,17.6,72.9,Overcast,0.0,...,1.255273,0.477121,0.698970,1.255273,1.079181,0.000000,0.000000,2.635484,0.954243,0.602060

In [17]:
dataframe.groupby('category',axis=1)